In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.3 MB 6.7 MB/s eta 0:00:02
   -- ------------------------------------- 0.8/12.3 MB 6.7 MB/s eta 0:00:02
   ------ --------------------------------- 2.1/12.3 MB 3.3 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.3 MB 3.4 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.3 MB 3.4 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.3 MB 2.8 MB/s eta 0:00:04
   -------------- ------------------------- 4.5/12.3 MB 2.9 MB/s eta 0:00:03
   ----------------- ---------------------- 5.2/12.3 MB 3.0 MB/s eta 0:00:03
   ------------------- -------------------- 6.0/12.3 MB 3.1 MB/s eta 0:00:03
   --------------------- ------------------ 6.6/12.3 MB 3.1 MB/s eta 0:00:02
   ----------------------- ---------------- 7.1/12.3 MB 3.1 MB/s eta 0:00:02
   ----------

In [ ]:
import numpy as np
#create array using numpy
# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)
print("type of array:", type(array_1d))
print("Shape:", array_1d.shape)


1D Array: [1 2 3 4 5]
type of array: <class 'numpy.ndarray'>
Shape: (5,)


In [ ]:
#1d array 
array_2d = np.array([1, 2, 3, 4, 5])
array_2d.reshape(1,5) #1 row 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
#2d array 
array_2d=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(array_2d)
array_2d.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [11]:
np.arange(0,10,2).reshape(5,1) #start , end , step

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [5]:
import numpy as np
np.ones((3,4)) #3 rows 4 columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.zeros((3,4)) #3 rows 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
#identity matrix
np.eye(4) #4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.sum()) #sum of all elements
print("shape:",arr.shape)
print("number of dimensions:",arr.ndim)
print("data type:",arr.dtype)
print("size:",arr.size) #total number of elements
print("type:",type(arr))
print("sum of columns:",arr.sum(axis=0)) #sum of each column
print("sum of rows:",arr.sum(axis=1)) #sum of each row


In [8]:
#numpy vectorized operations
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

print("Addition:",a+b)
print("Subtraction:",b-a)
print("Multiplication:",a*b)
print("Division:",b/a)
print("Exponentiation:",a**2)
print("Square Root:",np.sqrt(a))
print("Sine:",np.sin(a))
print("Cosine:",np.cos(a))
print("Logarithm:",np.log(a))
print("Exponential:",np.exp(a))
print("Maximum:",np.maximum(a,b))
print("Minimum:",np.minimum(a,b))
print("Mean of a:",np.mean(a))
print("Standard Deviation of a:",np.std(a))
print("Dot Product:",np.dot(a,b))
# --- IGNORE ---

Addition: [ 6  8 10 12]
Subtraction: [4 4 4 4]
Multiplication: [ 5 12 21 32]
Division: [5.         3.         2.33333333 2.        ]
Exponentiation: [ 1  4  9 16]
Square Root: [1.         1.41421356 1.73205081 2.        ]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Cosine: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
Logarithm: [0.         0.69314718 1.09861229 1.38629436]
Exponential: [ 2.71828183  7.3890561  20.08553692 54.59815003]
Maximum: [5 6 7 8]
Minimum: [1 2 3 4]
Mean of a: 2.5
Standard Deviation of a: 1.118033988749895
Dot Product: 70


In [28]:
# Create an array of 4 columns and 3 rows
array= np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("3D Array:\n", array)

3D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#access an element in this array 
print("Element at index 7:", array[0][2])  # Output: 3

Element at index 7: 3


In [ ]:
array[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
array[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [35]:
array[0:2,2:]

array([[3, 4],
       [7, 8]])

In [36]:
array[0][2]=99
array

array([[ 1,  2, 99,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
#statistics with numpy
data = np.array([12, 15, 14, 10, 18, 20, 22, 19, 17, 16])
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
variance = np.var(data)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)
# --- IGNORE ---


Mean: 16.3
Median: 16.5
Standard Deviation: 3.4942810419312296
Variance: 12.21


In [38]:
#logical operations with numpy
arr = np.array([10, 15, 20, 25, 30])
greater_than_20 = arr > 20
less_than_25 = arr < 25
print("Elements greater than 20:", arr[greater_than_20])
print("Elements less than 25:", arr[less_than_25])  
# --- IGNORE ---


Elements greater than 20: [25 30]
Elements less than 25: [10 15 20]
